#!/usr/bin/env bash

# Root level functions requiring password for mx-samba-config

# Find binaries
_update_rc=$(which update-rc.d)
_systemctl=$(which systemctl)
_service=$(which service)

# Service names for MX
_smbd="smbd"
_nmbd="nmbd"

# Service names for non-MX systems
if [ -x "$_systemctl" ]; then
    if "$_systemctl" list-unit-files smb.service 2>&1 > /dev/null ; then
        _smbd="smb"
    fi
    if "$_systemctl" list-unit-files nmb.service 2>&1 > /dev/null ; then
        _nmbd="nmb"
    fi
fi

# Disable/enable on both systemd and sysV
# Need to run both update-rc.d and systemctl on MX because we have two init systems

enablesamba()
{
if [ -x "$_update_rc" ]; then
    "$_update_rc" $_smbd remove
    "$_update_rc" $_nmbd remove
    "$_update_rc" $_smbd defaults
    "$_update_rc" $_nmbd defaults
fi
if [ -x "$_systemctl" ]; then
    "$_systemctl" unmask $_smbd
    "$_systemctl" unmask $_nmbd
    "$_systemctl" enable $_smbd
    "$_systemctl" enable $_nmbd
fi
}

disablesamba()
{
if [ -x "$_update_rc" ]; then
    "$_update_rc" $_smbd remove
    "$_update_rc" $_nmbd remove
fi
if [ -x "$_systemctl" ]; then
    "$_systemctl" disable $_smbd
    "$_systemctl" disable $_nmbd
    "$_systemctl" mask $_smbd
    "$_systemctl" mask $_nmbd
fi
}

addsambauser()
{
echo -ne "$pass\n$pass" | smbpasswd -as "$user"
exit $?
}

removesambauser()
{
pdbedit --delete "$user"
exit $?
}

changesambapasswd()
{
echo -ne "$pass\n$pass" | smbpasswd -U "$user"
exit $?
}

startsamba()
{
if [ -x "$_systemctl" ]; then
    MASKED=$("$_systemctl" is-enabled smbd)
    "$_systemctl" unmask $_smbd
    "$_systemctl" unmask $_nmbd
fi

if [ -x "$_service" ]; then
    "$_service" $_smbd start
    "$_service" $_nmbd start
elif [ -x "$_systemctl" ]; then
    "$_systemctl" start $_smbd
    "$_systemctl" start $_nmbd
fi

if [[ -x "$_systemctl" && $MASKED == "masked" ]]; then
    "$_systemctl" mask $_smbd
    "$_systemctl" mask $_nmbd
fi

exit $?
}

stopsamba()
{
if [ -x "$_service" ]; then
    "$_service" $_smbd stop
    "$_service" $_nmbd stop
elif [ -x "$_systemctl" ]; then
    "$_systemctl" stop $_smbd
    "$_systemctl" stop $_nmbd
fi

exit $?
}

main()
{
case $1 in
    startsamba)  startsamba
                 ;;
    stopsamba)  stopsamba
                 ;;
    enablesamba)  enablesamba
                 ;;
    disablesamba)  disablesamba
                 ;;
    addsambauser)  user="$3"
                   pass="$2"
                   addsambauser
                   ;;
    removesambauser)  user="$2"
                      removesambauser
                   ;;
    changesambapasswd)  user="$3"
                   pass="$2"
                   changesambapasswd
                   ;;
esac
}

main "$@"
